backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented

# This line should *not* be indented
media_folder: "assets/images/posts" # Media files will be stored in the repo under images/uploads

collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{day}}-{{month}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        pattern: ['.{1,}', "Must have at least 1 characters"]
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Newsletter", name: "newsletter", widget: "boolean", default: false}
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - label: "Author"
        name: "author"
        widget: "string"
        default: "Amando Abreu"
      - label: "Category"
        name: "category"
        widget: "string"
        required: false
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - name: "built"
    label: "Robot"
    folder: "_built"
    create: true
    slug: "{{year}}-{{day}}-{{month}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        pattern: ['.{1,}', "Must have at least 1 characters"]
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Newsletter", name: "newsletter", widget: "boolean", default: false}
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - label: "Author"
        name: "author"
        widget: "string"
        default: "Amando Abreu"
      - label: "Category"
        name: "category"
        widget: "string"
        required: false
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - name: "book"
    label: "Book"
    folder: "_read"
    create: true
    slug: "{{year}}-{{day}}-{{month}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        pattern: ['.{1,}', "Must have at least 1 characters"]
      - {label: "Layout", name: "layout", widget: "hidden", default: "read"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Newsletter", name: "newsletter", widget: "boolean", default: false}
      - {label: "Cover as header?", name: "cover_header", widget: "boolean", default: true}
      - {label: "Comments", name: "comments", widget: "boolean", default: true}
      - label: "Author"
        name: "author"
        widget: "string"
        default: "Amando Abreu"
      - label: "Book Author"
        name: "book_author"
        widget: "string"
        default: ""
      - label: "Category"
        name: "category"
        widget: "string"
        required: false
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}