backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/images/posts" # Media files will be stored in the repo under images/uploads

collections:
  - name: "wrote"
    label: "Post"
    folder: "_posts"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        pattern: ['.{20,}', "Must have at least 20 characters"]
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}